### ISSUE TITLE
Loading css failed

### ISSUE THREAD

**Issue by replusminus** [stimulus-components/stimulus-lightbox#10]
using rails 7 with stimulus and I'm not able to load the css in the application.js with

```javascript 
import 'lightgallery/css/lightgallery.css' 
```

due to error

```Uncaught TypeError: Failed to resolve module specifier "lightgallery/css/lightgallery.css". Relative references must start with either "/", "./", or "../".```

as indicated in ```https://www.stimulus-components.com/docs/stimulus-lightbox/``` under usage section

**Comment by myanch200** [comment]
I am having the same issue, I had to download the file myself, but then I have the problem of loading the fonts as well

**Comment by Jessicasciani** [comment]
Hello
Any update about this by any chance?
I have the same issue

**Comment by MSchmidt** [comment]
Same. But even it would work, I don't want a lightbox to load it's own fonts. Would be great to have something ligher as dependency.

**Comment by JuanSantamariaCol** [comment]
> I am having the same issue, I had to download the file myself, but then I have the problem of loading the fonts as well

how  you to that ? I have the same error, when I import by import 'lightgallery/css/lightgallery.css' the application.js not working

**Comment by guillaumebriday-pa** [comment]
You cannot import CSS in JS without modules bundler like Webpack or Vite. It seems that you're using import-maps here which is not compatible. 

So you can either use a modules bundler, or import CSS with Sprockets or in your CSS file or manually 👍
