### ISSUE TITLE
Replace LightGallery.js with a fully-open source alternative?

### ISSUE THREAD

**Issue by excid3** [stimulus-components/stimulus-lightbox#2]
LightGallery.js's license has a commercial license: 

>lightGallery.js is a free and open-source library, however, if you are using the library for business, commercial sites, projects, and applications, the Commercial license is the appropriate license. With this option, your source code is kept proprietary.

Would be nice if stimulus-lightbox had something everyone could use instead.

**Comment by guillaumebriday** [comment]
thanks @excid3! I wasn't aware of that license and that would be definitely nice to have something else to use.

Do you recommend another library?

**Comment by excid3** [comment]
I was actually looking for one, so I don't have specific recommendations. This looks pretty good though: https://basiclightbox.electerious.com/

I just was looking for a lightbox + YouTube embed for a homepage. 👍

**Comment by guillaumebriday** [comment]
I need to try it before switching but it looks cool!

**Comment by cmirnow** [comment]
Console warning:
`lightGallery: 0000-0000-000-0000 license key is not valid for production use`
I have a license key. Please tell me how I can enter this key after
`yarn add stimulus-lightbox`
?
Thank you for the answer.

**Comment by johnchambers** [comment]
Hey @cmirnow did you figure out how to add a license key?

**Comment by cmirnow** [comment]
> Hey @cmirnow did you figure out how to add a license key?

Hi. 
No. I removed stimulus-lightbox and installed lightgallery.js. This solved the problem.
NB. This is a great image gallery. I recommend it.

**Comment by guillaumebriday** [comment]
Maybe https://github.com/dimsemenov/photoswipe could be a good alternative?

What do you think?

**Comment by guillaumebriday** [comment]
Moved to https://github.com/stimulus-components/stimulus-components/issues/107
