### ISSUE TITLE
Can we load modules

### ISSUE THREAD

**Issue by jfsenechal** [stimulus-components/stimulus-lightbox#3]
hi

Can we load modules like 

```js
import lgThumbnail from 'lightgallery/plugins/thumbnail'
import lgZoom from 'lightgallery/plugins/zoom'
```

**Comment by guillaumebriday** [comment]
Hum there are no plugins if these folders right?

You could refer to the plugin you are looking for in order to install it with this package I guess

**Comment by jfsenechal** [comment]
Ho

I'm sorry I confused

https://www.lightgalleryjs.com/docs/getting-started/

and

https://sachinchoolur.github.io/lightgallery.js/
