### ISSUE TITLE
Access lightGallery instance when extending Lightbox controller

### ISSUE THREAD

**Issue by m-idler** [stimulus-components/stimulus-lightbox#6]
Currently the lightgallery is initialized in the connect method:
```
  connect() {
    lightGallery(this.element, __spreadValues(__spreadValues({}, this.defaultOptions), this.optionsValue));
  }
```
and as far as I can see, there isn't a possibility to call a method of this instance (e.g. `openGallery` triggered by a click event) when extending the Lightbox controller class.

Is there anything I don't see? Would it be possible and make sense, to get access to the lightgallery instance via a variable or getter method?

**Comment by guillaumebriday** [comment]
You might want something like 

```js
connect () {
  this.instance = lightGallery(this.element, {...})
}
```

Right?

**Comment by m-idler** [comment]
> You might want something like
> 
> ```js
> connect () {
>   this.instance = lightGallery(this.element, {...})
> }
> ```
> 
> Right?

Yes, I guess it's just that.

My current solution, which still uses the existing `connect` method is based on the lightbox init event:
```
    lightboxInstance;

    connect() {
        this.element.addEventListener('lgInit', this._onInitLightbox.bind(this));

        super.connect()
    }

    disconnect() {
        this.element.removeEventListener('lgInit', this._onInitLightbox);
    }

    open(event) {
        this.lightboxInstance.openGallery();
    }

    _onInitLightbox(event) {
        this.lightboxInstance = event.detail.instance;
    }

**Comment by guillaumebriday** [comment]
There you go @m-idler 👉 https://github.com/stimulus-components/stimulus-lightbox/releases/tag/v3.1.0

Thanks for the issue
