### ISSUE TITLE
Issues with esbuild and lightgallery assets 

### ISSUE THREAD

**Issue by jfeust** [stimulus-components/stimulus-lightbox#8]
Using ESBuild with `import 'lightgallery/css/lightgallery.css'`

```
01:14:46 js.1     | ✘ [ERROR] No loader is configured for ".gif" files: node_modules/lightgallery/images/loading.gif
01:14:46 js.1     |
01:14:46 js.1     |     node_modules/lightgallery/css/lightgallery.css:504:18:
01:14:46 js.1     |       504 │   background: url("../images/loading.gif") no-repeat scroll cente...
```

Also happens with .ttf, .svg, and other assets referenced in the lightgallery css.

**Comment by MarcManiez** [comment]
Hi @jfeust I ran into this as well, and you can solve this by adding flags to esbuild inside the `build` command of your `package.json`. 

`esbuild [your_entry_points] --bundle --sourcemap --outdir=app/assets/builds --public-path=assets --loader:.gif=file --loader:.svg=text --loader:.ttf=file --loader:.woff=file --loader:.woff2=file`

Happy coding!

**Comment by guillaumebriday** [comment]
Yep this depends of your module bundler 👍
